<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="htmlplot.xsl"?>

<!DOCTYPE plotscript [
	<!ELEMENT plotscript (section+)>
	<!ATTLIST plotscript version CDATA "wip" datecode CDATA "???">
	<!ATTLIST plotscript show-alias CDATA "yes">
	<!ELEMENT section (description?,(command|reference|section)+)>
	<!ATTLIST section title CDATA #REQUIRED constants (yes|no) #IMPLIED topics (yes|no) #IMPLIED>
	<!ELEMENT reference EMPTY>
	<!ATTLIST reference ref IDREF #REQUIRED>
	<!ELEMENT command ((canon+,shortname,altcommand*,added?,deprecated?,description,altcommand*,example*,seealso?) |
					   (alias,shortname,added?,deprecated?))>
	<!ATTLIST command id ID #REQUIRED>
	<!ELEMENT altcommand (canon*,shortname)>
	<!ATTLIST altcommand id ID #IMPLIED show-alias CDATA "yes"  alias (show|hide) "show">
	<!ELEMENT canon      (#PCDATA)>
	<!ELEMENT altcanon   (#PCDATA)>
	<!ELEMENT shortname   (#PCDATA)>
	<!ELEMENT added     (#PCDATA)>
	<!ELEMENT deprecated     (#PCDATA)>
	<!ELEMENT description ANY>
	<!ELEMENT example     (#PCDATA)>
	<!ATTLIST example c IDREF #IMPLIED>
	<!ELEMENT alias       (#PCDATA)>
	<!ELEMENT seealso (ref+)>

	<!ELEMENT note         ANY>
	<!ELEMENT warn         ANY>
	<!ELEMENT danger       ANY>
	<!ELEMENT ref          (#PCDATA)>
	<!ELEMENT secref       (#PCDATA)>
	<!ELEMENT ul           (li*)>
	<!ELEMENT li           ANY>
	<!ELEMENT a            ANY>
	<!ATTLIST a            href CDATA #IMPLIED>
	<!ELEMENT lb           (#PCDATA)>
	<!ELEMENT p            (#PCDATA)>
	<!ELEMENT tt           ANY>
	<!ELEMENT b            (#PCDATA)>
]>
<!--

DOCUMENTATION FOR THIS XML FILE:

This markup (hereby refered to as PDL (Plotscript Dictionary Language)) is
designed to reduce the time spent maintaining the Plotscripting Dictionary, and
to enable easier porting to other formats.

The root element is the <plotscript> element. It has a 'version' attribute,
the engine version it applies to. Update this when releasing.

In <plotscript>, there is a series of <section> elements, each with a title
attribute. These are to group the plotscripting commands into logical groups,
such as <section title="Wait Commands"> or <section title="Math Operators">.
Sections can be nested inside each other. And commands that appear after
a subsection will be reorderd in front of all subsections.

The heart of the PDL are the <command> elements inside the <section>s. It has a
single attribute, id. This is essentially the whitespace stripped version of the
command (the "wait for text box" command would have an id of "waitfortextbox").
This is used to uniquely identify each command. It's used in many ways, from
crosslinking command entries to generating a file for HssEd to use.

Inside the <command> element are subelements, in this order:
Case 1: Full command definition
  <canon>*      - This is the "canonical" form of the command: the fully spaced
                  command with parameter prototypes. Can appear multiple times to
		  show alternative arg lists; only the first is shown in command
		  indexes. (Use <altcommand> instead for aliases). Example:
		  <canon>import globals (slot, first, last)</canon>
                  <canon>import globals (slot, id)</canon>
  <shortname>   - This is the short version of the command, used for crosslinking,
                  indexes, etc. It is the <canon> element, minus the parameters.
                  Example: import globals
  <altcommand>* - This defines an alias to the command which is documented
                  together with it, but which appears separately in command
		  indexes (if it contains a <canon>) and can be linked to
		  separately. Must have an id="" attribute and <shortname>
		  subelement, and usually has one or more <canon>s. If there's no
		  canon then <shortname> is used for links but no 'canon' line
		  appears in the command definition.
		  "Alias:" is displayed before the command, unless you add
		  alias="hide".
  <added>       - Version this was added in. Not used!
  <deprecated>  - Version this was deprecated in. Not used!
  <description> - This is a paragraph (or more) of text describing what the
                  command does, and how to use it. Use <lb/> to put paragraphs
                  in, and <p></p> when referring to a parameter (to avoid user
                  confusion). No HTML is allowed (at this time).
                  You can also embed <example> blocks inside <description> blocks
                  instead of having them trail afterwards. Example: Well, it
                  would be pretty long...
  <example>*    - Finally, commands may  have some sort of example usage of the
                  the command. You can put this inside <description> instead;
		  that way you can put more text after/between the example(s).
                  It will be displayed in a mono-space font suitable for code.
                  But, be sure to format it properly:
                  Example:
                  <example># first example line has no line-break
# the second (and more) lines should have no indentation
# and so forth</example>

As an alternative to <altcommand> you can also define aliases which have
separate entries. This is probably mainly useful for obsolete aliases which
you want to hide in a different section:

Case 2: Alias command definition
  <alias>       - If a command is an alias to another command (or is so closely
                  related that they're in the same entry, use the <alias> element. Put
                  the ID of the real command in here. Example: begin
  <shortname>   - Aliases also need a short name, since they are technically
                  different from their alias. Example: end

Additionally, if you want a command to appear in multiple sections,
define it once and place references to it elsewhere.
  <reference>   - Has a single attribute, 'ref', and no contents.

Basically, you should be able to examine the entries that already exist. It's
fairly self evident what everything does.

If you have xmllint installed you can run update-html.sh and it'll tell you
about all kinds of critical errors that your web browser will probably silently
ignore by throwing away what it doesn't understand.


These are cut-and-paste copies of <command> elements, so you don't have to type
everything out 10000000000 times. They are also indented properly for this file.

#===== Full description

		<command id="">
			<canon></canon>
			<shortname></shortname>
			<description></description>
			<example></example>
		</command>

#===== Full description with borrowed example

		<command id="">
			<canon></canon>
			<shortname></shortname>
			<description></description>
			<example c="">
		</command>

#===== Alias

		<command id="">
			<alias></alias>
			<shortname></shortname>
		</command>

#===== Reference

		<reference ref="" />

#=====

Which reminds me: Indentation. For each "level" you go down in the hierarchy,
you indent once. Many code specific editors will maintain this indentation level
for until you explicitly change it, so it isn't difficult. Notepad users will
have to do it manually, but you MUST do it. Remember: 1 indent = 1 tab.
(However, subsections are not indented, in order to keep all commands at the
same level.)

"Mono means 'one'. Rail means 'rail'. And that concludes our training."
	~ Monorail guy, Simpsons

-->
<plotscript version="hróðvitnir" datecode="2021-09-09">

	<section title="Declarations">
		<command id="plotscript">
			<canon>plotscript, name, argumentnames (statements)</canon>
			<shortname>plotscript</shortname>
			<description>
				The plotscript command contains a list of commands that can be triggered directly by an event in your game.
				<lb/>
				Plotscript starts with the keyword plotscript, a comma, and then the name of the plotscript.
				If there are any arguments to the script, you list their names separated by commas after the name of
				the script, optionally with default values declared like <tt>arg = defaultvalue</tt>.
				<lb/>
				Then comes the text of the script.
				It is enclosed in <ref>begin</ref> and <ref>end</ref> statements.
				Scripts that are defined as plotscripts can be called directly from "trigger" events in your game,
				or by name within other scripts.
				<note>
					What's the difference between <p>plotscript</p> and <ref>script</ref>?
					<lb/>
					The only difference is that plotscripts are listed in the game editor,
					allowing them to be attached to triggers
					(such as the new-game script),
					while plain <tt>script</tt>s are hidden and can't be selected.
					(Technically you can use a <tt>script</tt> as a trigger,
					but only by using a command like <ref>setdeathscript</ref>.)
				</note>
			</description>
			<example># example of a simple script
plotscript,my first script,begin
	# commands go here
end</example>
			<example># example of a script with arguments
# (It can called with between 1 and 3 arguments.)
plotscript,my fancy script,fe,fi=0,fo=0,begin
	# commands go here,
	# and they can use the aruments fe, fi, and fo
	# that where passed to the script
end</example>
		</command>
		<command id="script">
			<canon>script, name, argumentnames (statements)</canon>
			<shortname>script</shortname>
			<description>The script command contains a list of commands. Script starts with the keyword script, a comma, and then the name of the script. If there are any arguments to the script, you list their names separated by commas after the name of the script with optional default values. Then comes the text of the script. It is enclosed in <ref>begin</ref> and <ref>end</ref> statements. Scripts that are defined as script cannot be called directly from events in your game. They can only be called by name within other scripts. To make a script that can be run directly from your game, use <ref>plotscript</ref>.</description>
			<example># example of a simple script
script,my first script,begin
	# commands go here
end</example>
			<example># Example of a script with arguments
# (It can called with between 1 and 3 arguments.)
script,my fancy script,fe,fi=0,fo=0,begin
	# Commands go here,
	# and they can use the aruments fe, fi, and fo
	# that where passed to the script.
end</example>
		</command>
		<command id="subscript">
                  
			<canon>subscript, name, argumentnames (statements)</canon>
			<shortname>subscript</shortname>
			<description><p>subscript</p> is just like <ref>script</ref> except that it must placed inside another script (or even inside another subscript). See <ref>script</ref> for details of syntax of arguments. The difference from a regular script is that a subscript can only be called from its parent script (or some other subscript), and it can directly access its parent script's variables in addition to its own arguments and variables. Subscripts can be useful when you have some piece of repeated code that you want to "de-duplicate" by moving into another script which you can call repeatedly, but without having to turn local variables into global variables.</description>
			<example># Some nearby NPCs move into a line to the north of the hero
plotscript, line up soldiers, begin
	show textbox(32)  # "Yes sir!"
	wait for textbox
	suspend player
	set hero direction(me, up)
	variable (x, y)
	# The position of the start of the line
	x := hero X(me) -- 2
	y := hero Y(me) -- 4
	subscript, line up NPC, npc, begin
		# Increment X to get next position in the line
		x += 1
		walk NPC to X(npc, x)
		wait for NPC(npc)
		walk NPC to Y(npc, y)
		wait for NPC(npc)
		set NPC direction(npc, down)
	end
	# NPCs move one at a time
	line up NPC(1)
	line up NPC(3)
	line up NPC(11)
	line up NPC(10)
	line up NPC(5)
	resume player
end</example>
		</command>
		<command id="globalvariable">
			<canon>global variable (id,name)</canon>
			<shortname>global variable</shortname>
			<description>Creates a global variable that can be used in any script. The first argument to the global variable declaration is a unique ID number. The second argument is the name of the variable. The ID number for a global variable is a number from 0 to 16383. Each global variable must have a unique number, but this number will not conflict with the ID numbers you use for scripts. It is all right to have a script and a global variable with the same ID number. See also <ref>variable</ref></description>
			<example># any script can read and set the value of a global
global variable(1,mini game score)</example>
		</command>
		<command id="variable">
			<canon>variable (name)</canon>
			<shortname>variable</shortname>
			<description>Creates a local variable that can only be used inside the script where it was created. The value of this variable is lost when the script ends. If you need a variable who&apos;s value persists between calls to a script, or that is automatically saved when the player saves their game, you will need to use a <ref>globalvariable</ref> instead.</description>
			<example>variable(points) # make a new variable
variable+=1 # add one to it</example>
		</command>
		<command id="defineconstant">
			<canon>define constant (number,name)</canon>
			<shortname>define constant</shortname>
			<description>
				Creates a global constant.
				The first argument is the number that the constant will represent, and the second argument is the name of the constant.
				Use constants to replace commonly used numbers with friendly names.
				The following are some general purpose constants have been defined for you
				(there are hundreds more intended for specific commands):
				<lb />
				<tt>zero</tt> <tt>one</tt> <tt>two</tt> <tt>three</tt> <tt>four</tt> <tt>five</tt> <tt>six</tt> <tt>seven</tt> <tt>eight</tt> <tt>nine</tt> <tt>ten</tt>
				<ref>false</ref> <ref>true</ref> <ref>off</ref> <ref>on</ref>
				<ref>north</ref> <ref>east</ref> <ref>south</ref> <ref>west</ref>
				<ref>up</ref> <ref>down</ref> <ref>left</ref> <ref>right</ref>
				<ref>me</ref>
				<ref>none</ref>
			</description>
		</command>
		<command id="include">
			<canon>include, filename</canon>
			<shortname>include</shortname>
			<description>The include command effectively inserts another text file into your script. It is followed by a single filename that tells what file will be included. This can be used to organise your scripts and other definitions like <ref>defineconstant</ref> into multiple files. The filename can include a path, for example <p>include, ..\utility scripts\math.hss</p>. You can optionally include quote marks around the filename, e.g. <p>include, "misc.hss"</p>, which causes normal string parsing (for example, allowing a # character in a filename). <lb/>Previously every plotscript file had to start with <p>include, plotscr.hsd</p> but this is now optional. <p>plotscr.hsd</p>, <p>scancode.hsi</p>, and the exported <p>your game name.hsi</p> file are all automatically included.</description>
			<example>include, cutscenes.hss  # All scripts for cutscenes
include, ..\utility scripts\math.hss  # A few useful scripts shared between multiple games</example>
		</command>
	</section>

	<section title="Math, Comparison, and Logic Operators">

		<section title="Working with Variables">
		<command id="setvariable">
			<canon>variable := value</canon>
			<shortname>:=</shortname>
			<description>
				This command assigns a new value to a variable.
				If you do not specify the new value, the variable will be reset to zero.
				This command works exactly the same for global and local variables.
				<lb/>
				The <tt>:=</tt> operation actually returns <p>value</p>, so you can use it
				as an expression, for example in <tt>temp1 := (temp2 := 1)</tt>.
			</description>
		</command>
		<command id="increment">
			<canon>increment (variable,amount)</canon>
			<shortname>increment</shortname>
			<description>
				or<lb/><p>variable += amount</p>
				<lb/>
				This command adds an amount to the current value of a variable.
				If you do not specify the amount, then the variable will be incremented by one.
				This command works exactly the same for global and local variables.
				<lb/>
				The <tt>+=</tt> operation actually returns the new value of <p>variable</p>,
				so you can use it as an expression, for example in <tt>while ((index += 1) &lt; 10)</tt>.
			</description>
		</command>
		<command id="decrement">
			<canon>decrement (variable,amount)</canon>
			<shortname>decrement</shortname>
			<description>
				or<lb/><p>variable -= amount</p>
				<lb/>
				This command subtracts an amount from the current value of a variable.
				If you do not specify the amount, then the variable will be decremented by one.
				This command works exactly the same for global and local variables.
				<lb/>
				The <tt>-=</tt> operation actually returns the new value of <p>variable</p>,
				so you can use it as an expression, for example in <tt>while (index -= 1)</tt>.
			</description>
		</command>
		<command id="readglobal">
			<canon>read global (id)</canon>
			<shortname>read global</shortname>
			<description>A function that returns the value of a global variable using its ID number instead of its name. Why would you want to do a silly thing like that? Because it allows you to simulate simple fake arrays, in the old C-pointer style.</description>
			<seealso>
				<ref>writeglobal</ref>
			</seealso>
		</command>
		<command id="writeglobal">
			<canon>write global (id,value)</canon>
			<shortname>write global</shortname>
			<description>A function that writes a value into a global variable using its ID number instead of its name. Why would you want to do a silly thing like that? Because it allows you to simulate simple fake arrays, in the old C-pointer style</description>
			<seealso>
				<ref>readglobal</ref>
			</seealso>
		</command>
		</section>		<!--Working with variables-->

		<command id="add">
			<canon>number + number</canon>
			<shortname>add</shortname>
			<description>Adds two values together and returns the result. This can also be written as <p>add(number,number)</p></description>
		</command>
		<command id="subtract">
			<canon>number -- number</canon>
			<shortname>subtract</shortname>
			<description>Subtracts the second number from the first number and returns the result. It is necessary to use the double minus so that HSPEAK.EXE can tell the difference between subtraction, and a minus sign that indicates a negative number. You can also write <p>subtract(number,number)</p></description>
		</command>
		<command id="multiply">
			<canon>number * number</canon>
			<shortname>multiply</shortname>
			<description>Multiplies two values together and returns the result. This can also be written as <p>multiply(number,number)</p></description>
		</command>
		<command id="divide">
			<canon>number / number</canon>
			<shortname>divide</shortname>
			<description>Divides the second number into the first number and returns the result. The result is rounded down to an integer. This can also be written as <p>divide(number,number)</p></description>
		</command>
		<command id="modulus">
			<canon>number,mod,number</canon>
			<shortname>mod</shortname>
			<description>Divides the second number into the first number and returns the remainder. This can also be written as <p>modulus(number,number)</p></description>
		</command>
		<command id="exponent">
			<canon>number ^ power</canon>
			<shortname>^</shortname>
			<description>Raises a number to a power and returns the result. (If the result is too large and overflows no error occurs: the value is simply wrapped around a 32 bit signed integer.) This can also be written as <p>exponent(number,power)</p></description>
		</command>
		<command id="abs">
			<canon>abs (number)</canon>
			<shortname>abs</shortname>
			<description>Returns the absolute value of a value. That is, negative values are made positive and others are unchanged: abs(-14) is 14, and abs(14) is 14.</description>
		</command>
		<command id="sign">
			<canon>sign (number)</canon>
			<shortname>sign</shortname>
			<description>Returns -1 if <p>number</p> is negative, 0 if it is 0, and 1 if <p>number</p> is positive.</description>
		</command>
		<command id="sqrt">
			<canon>sqrt (number)</canon>
			<shortname>sqrt</shortname>
			<description>Returns the squareroot of a number, rounded to the nearest integer.</description>
		</command>
		<command id="equal">
			<canon>number == number</canon>
			<shortname>==</shortname>
			<description>Checks to see if the two numbers are equal. If they are equal it returns true, otherwise it returns false. This can also be written as <p>equal(number,number)</p></description>
		</command>
		<command id="notequal">
			<canon>number &lt;> number</canon>
			<shortname>&lt;></shortname>
			<description>Checks to see if the two numbers are not equal. If they are not equal it returns true. If they are equal it returns false. This can also be written as <p>not equal(number,number)</p></description>
		</command>
		<command id="lessthan">
			<canon>number &lt; number</canon>
			<shortname>&lt;</shortname>
			<description>Checks to see if the first number is less than the second number. If it is, it returns true, otherwise it returns false. This can also be written as <p>less than(number,number)</p> and as <p>number &lt;&lt; number</p></description>
		</command>
		<command id="greaterthan">
			<canon>number &gt; number</canon>
			<shortname>&gt;</shortname>
			<description>Checks to see if the first number is greater than the second number. If it is, it returns true, otherwise it returns false. This can also be written as <p>greater than(number,number)</p> and as <p>number &gt;&gt; number</p></description>
		</command>
		<command id="lessthanorequalto">
			<canon>number &lt;= number</canon>
			<shortname>&lt;=</shortname>
			<description>Checks to see if the first number is less than or equal to the second number. If it is, it returns true, otherwise it returns false. This can also be written as <p>less than or equal to(number,number)</p></description>
		</command>
		<command id="greaterthanorequalto">
			<canon>number >= number</canon>
			<shortname>&gt;=</shortname>
			<description>Checks to see if the first number is greater than or equal to the second number. If it is, it returns true, otherwise it returns false. This can also be written as <p>greater than or equal to(number,number)</p></description>
		</command>
		<command id="and">
			<canon>value,and,value</canon>
			<shortname>and</shortname>
			<description>Returns the bitwise AND of both values. In other words, for each bit in each value, they are compared to see if they are both "1". If they are, the result bit is set to 1. Otherwise, it's set to 0.</description>
			<seealso><ref>logicaland</ref></seealso>
		</command>
		<command id="or">
			<canon>value,or,value</canon>
			<shortname>or</shortname>
			<description>Returns the bitwise OR of both values. In other words, for each bit in each value, they are compared to see if either bit is "1". If one is, the result bit is set to 1. Otherwise, it's set to 0.</description>
			<seealso><ref>logicalor</ref></seealso>
		</command>
		<command id="xor">
			<canon>value,xor,value</canon>
			<shortname>xor</shortname>
			<description>Returns the bitwise AND of both values. In other words, for each bit in each value, they are compared to see if either (but not both!) bit is "1". If ONE is, the result bit is set to 1. Otherwise, it's set to 0.</description>
			<seealso><ref>logicalxor</ref></seealso>
		</command>
		<command id="logicaland">
			<canon>value &amp;&amp; value</canon>
			<shortname>&amp;&amp;</shortname>
			<description>Returns true if both of the values are true (non-zero). If either of them is false, and returns false. This command uses shortcut evaluation: if the first argument is false, the second argument is never evaluated.</description>
		</command>
		<command id="logicalor">
			<canon>value || value</canon>
			<shortname>||</shortname>
			<description>Returns true if at least one of the values are true (non-zero). Only if both of them are false does or return false. This command uses shortcut evaluation: if the first argument is true, the second argument is never evaluated.</description>
		</command>
		<command id="logicalxor">
			<canon>value ^^ value</canon>
			<shortname>^^</shortname>
			<description>Returns true if one, but not both of the values are true (non-zero). If both of them are true, or both of them are false, ^^ returns false.</description>
		</command>
		<command id="not">
			<canon>not (value)</canon>
			<shortname>not</shortname>
			<description>Returns the logical complement/negation of a value. That is, it returns true (1) if the value is false (0), or false (0) if the value is true (non-zero).</description>
		</command>
		<command id="random">
			<canon>random (lownumber, highnumber)</canon>
			<shortname>random</shortname>
			<description>Returns a random integer in the range of the two numbers. The returned value will be greater than or equal to the first number, and less than or equal to the second number</description>
		</command>
		<command id="seedrandom">
			<canon>seed random (seed)</canon>
			<shortname>seedrandom</shortname>
			<description>
				Reseeds the random number generator.
				If you pass in a <p>seed</p> (number) other than 0, the random number generator will be seeded with that number,
				allowing for repeatable random sequences - <ref>random</ref> will always return the same sequence
				of random numbers afterwards. Each seed causes a completely different sequence.
				<lb/>
				If called with no argument (or <p>seed</p> = 0), this will reseed the random number generator to a new random sequence
				(which is useful only if you've previously called <tt>seed random(...)</tt> to put it into
				a predictable sequence.)
				<note>
					You don't need to call this command before using <ref>random</ref>.
					In fact, this command is useful only if you <b>don't</b> want completely random numbers.
				</note>
			</description>
			<seealso>
				<ref>random</ref>
			</seealso>
		</command>
		<command id="multdiv">
			<canon>multdiv (a, b, c)</canon>
			<shortname>multdiv</shortname>
			<description>
				Computes <tt>(a * b) / c</tt> with rounding, and without overflowing.
				The intermediate result is performed in floating point so that it won't overflow,
				and the final result is clamped to the range of a 32-bit integer.
				<lb/>
				This is equivalent to <tt>min(2^31 - 1, max(-2^31, round(1.0 * a * b / c)))</tt> in other languages.
			</description>
		</command>
	</section>

	<section title="Flow Control">
		<command id="begin">
			<canon>begin,other commands,end</canon>
			<shortname>begin</shortname>
			<description>
				<tt>begin</tt> is a synonym for <tt>(</tt> and <tt>end</tt> is a synonym for <tt>)</tt>.
				Parentheses are normally used for bracketing things that all fit on the same line,
				and begin/end statements are often used to enclose very long things such as whole
				scripts or long flow control blocks that take up several lines.
				For example, the following:
				<example>if (check tag(tag:have rusty sword)) then (show text box (5), wait for text box)</example>
				is equivalent to:
				<example>if (check tag(tag:have rusty sword)) then, begin
	show text box (5)
	wait for text box
end</example>
			</description>
		</command>
		<command id="end">
			<canon>end</canon>
			<shortname>end</shortname>
			<description>See <ref>begin</ref>.</description>
		</command>
		<command id="if">
			<canon>if(condition) then(commands) else(commands)</canon>
			<shortname>if</shortname>
			<description>The <p>if</p> statement checks the value of its condition, and if the value is <ref>true</ref> (actually, any value other than <ref>false</ref> (which is zero) counts as true), it runs the commands in the <p>then</p> block. If the value is <ref>false</ref>, it runs the commands in its <p>else</p> block. The conditional is usually a comparison operator such as <ref>equal</ref> or <ref>notequal</ref>, or a command which returns either true or false, such as <ref>checktag</ref>. The <p>else</p> is optional as long as you have a <p>then</p>, and the <p>then</p> is optional as long as you have an <p>else</p>. You can also place one or more <ref>elseif</ref>s after the <p>then</p> (or immediately after the <p>if</p> if you skip the <p>then</p>) instead of nesting multiple <p>if</p> statements.</description>
			<seealso><ref>elseif</ref></seealso>
		</command>
		<command id="elseif">
			<canon>... else if(condition) then(commands) ...</canon>
			<shortname>else if</shortname>
			<description>This can appear after an <ref>if</ref> or <ref>then</ref> block. It is a shortcut for <ref>else</ref> followed by <ref>if</ref> which lets you omit a pairs of brackets/<ref>begin</ref> and <ref>end</ref>, as this example shows:
			<example>if (inventory (item:apple)) then (
  show text box (10)  # "Apples! My favourite!"
) else if (inventory (item:orange)) then (
  show text box (11)  # "My, what a tasty looking orange..."
) else if (inventory (item:pear)) then (
  show text box (12)  # "Perhaps if you gave me that pear..."
) else (
  show text box (13)  # "Come back when you have something tasty for me!"
)</example>
			</description>
		</command>

		<command id="then">
			<alias>if</alias>
			<shortname>then</shortname>
		</command>
		<command id="else">
			<alias>if</alias>
			<shortname>else</shortname>
		</command>
		<command id="while">
			<canon>while(condition) do(commands)</canon>
			<shortname>while</shortname>
			<description>The while command checks the value of its condition, and if the value is <ref>true</ref> it runs the commands in the do block. It keeps checking the conditional and runs the do block over and over again until the conditional returns <ref>false</ref>. The conditional is usually an equality operator such as <ref>equal</ref> or <ref>notequal</ref>, or it is a check tag command.</description>
		</command>
		<command id="do">